name: Cypress E2E Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- CONFIGURATION PHP (Pour tes 3 Microservices) ---
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, dom, curl, libxml, sqlite3

      # lancement des services
      - name: Install & Start Microservices
        run: |
          cd auth-service && composer install && cp .env.example .env
          touch database/database.sqlite && php artisan migrate
          php artisan serve --port=8081 &

          cd ../core-service && composer install && cp .env.example .env
          touch database/database.sqlite && php artisan migrate
          php artisan serve --port=8082 &

          cd ../payment-service && composer install && cp .env.example .env
          touch database/database.sqlite && php artisan migrate
          php artisan serve --port=8083 &

      # Front end
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:5173"
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_TEST_KEY }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
